//
//  SJVideoPlayerLocalizedStringKeys.swift
//  Pods
//
//  Created by 畅三江 on 2019/11/27.
//

import Foundation

///
/// 本地化
///
/// 标识符为开放扩展点, 使用 typealias 而非封闭 enum。
public typealias SJVideoPlayerLocalizedStringKey = String

// 30 个本地化 key, 值 == 变量名 (原样保留字符串契约)。
// 注意拼写: NoNetwork / WiFiNetWork (大写 W)。

public let SJVideoPlayerLocalizedStringKeyLongPressSpeedupPlayback: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyLongPressSpeedupPlayback"
public let SJVideoPlayerLocalizedStringKeyNoNetwork: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyNoNetwork"
public let SJVideoPlayerLocalizedStringKeyWiFiNetWork: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyWiFiNetWork"
public let SJVideoPlayerLocalizedStringKeyCellularNetwork: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyCellularNetwork"
public let SJVideoPlayerLocalizedStringKeyReplay: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyReplay"
public let SJVideoPlayerLocalizedStringKeyRetry: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyRetry"
public let SJVideoPlayerLocalizedStringKeyReload: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyReload"
public let SJVideoPlayerLocalizedStringKeyLiveBroadcast: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyLiveBroadcast"
public let SJVideoPlayerLocalizedStringKeyCancel: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyCancel"
public let SJVideoPlayerLocalizedStringKeyDone: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyDone"
public let SJVideoPlayerLocalizedStringKeyUnstableNetworkPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyUnstableNetworkPrompt"
public let SJVideoPlayerLocalizedStringKeyCellularNetworkPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyCellularNetworkPrompt"
public let SJVideoPlayerLocalizedStringKeyNoNetworkPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyNoNetworkPrompt"
public let SJVideoPlayerLocalizedStringKeyPlaybackFailedPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyPlaybackFailedPrompt"
public let SJVideoPlayerLocalizedStringKeyRecordsPreparingPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyRecordsPreparingPrompt"
public let SJVideoPlayerLocalizedStringKeyRecordsToFinishRecordingPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyRecordsToFinishRecordingPrompt"
public let SJVideoPlayerLocalizedStringKeyExportsExportingPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyExportsExportingPrompt"
public let SJVideoPlayerLocalizedStringKeyExportsExportFailedPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyExportsExportFailedPrompt"
public let SJVideoPlayerLocalizedStringKeyExportsExportSuccessfullyPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyExportsExportSuccessfullyPrompt"
public let SJVideoPlayerLocalizedStringKeyUploadsUploadingPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyUploadsUploadingPrompt"
public let SJVideoPlayerLocalizedStringKeyUploadsUploadFailedPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyUploadsUploadFailedPrompt"
public let SJVideoPlayerLocalizedStringKeyUploadsUploadSuccessfullyPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyUploadsUploadSuccessfullyPrompt"
public let SJVideoPlayerLocalizedStringKeyScreenshotSuccessfullyPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyScreenshotSuccessfullyPrompt"
public let SJVideoPlayerLocalizedStringKeyAlbumAuthDeniedPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyAlbumAuthDeniedPrompt"
public let SJVideoPlayerLocalizedStringKeyAlbumSavingScreenshotToAlbumPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyAlbumSavingScreenshotToAlbumPrompt"
public let SJVideoPlayerLocalizedStringKeyAlbumSavedToAlbumPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyAlbumSavedToAlbumPrompt"
public let SJVideoPlayerLocalizedStringKeyOperationFailedPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyOperationFailedPrompt"
public let SJVideoPlayerLocalizedStringKeyDefinitionSwitchingPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyDefinitionSwitchingPrompt"
public let SJVideoPlayerLocalizedStringKeyDefinitionSwitchSuccessfullyPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyDefinitionSwitchSuccessfullyPrompt"
public let SJVideoPlayerLocalizedStringKeyDefinitionSwitchFailedPrompt: SJVideoPlayerLocalizedStringKey = "SJVideoPlayerLocalizedStringKeyDefinitionSwitchFailedPrompt"
